### ISSUE TITLE
"Collection was modified; enumeration operation may not execute" Error coming up randomly, after serveral hours of running.

### ISSUE THREAD

**Issue by tylerbeal** [Teun/BatchFlow#2]
Sorry if this is an incorrect report, but I've gone through my code so many times I don't know where the issue could be. Every collection I'm using is either concurrent, or modified to support async access. I would expect this error to pop up a little sooner than 10+ hours into the run were it an obvious mistake.

Has this behavior ever been observed before?

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at BatchFlow.TaskNode.Stop()
   at BatchFlow.Flow.Stop()
   at BatchFlow.TaskNode.Worker()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Teun** [comment]
This sounds like a problem with an internal collection. Do you have a clear reproduction path? Or does it just happen every now and then after a long time running?

**Comment by tylerbeal** [comment]
No clear repro path, just comes up after a long time running. Usually 24+ hours.

**Comment by Teun** [comment]
OK, I'll have a look at your stack trace. Maybe I can figure out the specific situation. It does look like an error of the library, not your code.

**Comment by tylerbeal** [comment]
Hey thanks! I'm still trying to look through my code to find any places I might be doing something dumb, just in case. Will let you know if I find something I've overlooked.

**Comment by Teun** [comment]
I think I found the problem. At the time of stopping the flow (this can happen intentionally or by exceptions or just completing), the procedure cleaning up the worker threads for a task could start cleaning them up at exactly the time when the worker thread itself finds out that there is no more work and shuts itself down.

Tricky race condition, but should be solved now. I have published a new release to nuget. Can you update and test?

**Comment by tylerbeal** [comment]
Hey I'm sorry I didn't get a chance to get back to you earlier. I have a higher load job running tonight, but the somewhat less intense one ran perfectly after the update. I'll keep you posted on how this goes tonight. Something around a million records to process.

**Comment by tylerbeal** [comment]
Well, so far no crashes from what I've seen. I'll call this closed.

Thanks again!

**Comment by Teun** [comment]
Awesome

**Comment by Franklin89** [comment]
Hey, I get the exact same exception if I add this ZIP Task:


            var zip = new TaskNode<string, string>((input, output) =>
            {
                var archivePath = $@"{exportFolder}\{archiveCount}.zip";

                ZipFile archive = null;

                if (!File.Exists(archivePath))
                {
                    archive = ZipFile.Create(archivePath);
                }
                else
                {
                    archive = new ZipFile(archivePath);
                }

                archive.BeginUpdate();
                archive.Add(input, Path.GetFileName(input));
                archive.CommitUpdate();
                archive.IsStreamOwner = false;
                archive.Close();
                archive = null;

                File.Delete(input);

                var fileInfo = new FileInfo(archivePath);
                if (fileInfo.Length > (50 * 1024 * 1024))
                {
                    archiveCount++;
                }

                output.Send(input);
            });

Any idea what the issue could be?
